const CONFIG={destination:'Pune Railway Station',original:400,saving:80,bReference:200,bFare:110,fee:10,otp:'2468',capacity:3,aPassengers:1,grace:2,candidates:[{id:'B',added:4,proximity:.3,solo:true,destination:'Pune Railway Station',available:true,reachable:true},{id:'C',added:10,proximity:.8,solo:true,destination:'Pune Railway Station',available:true,reachable:true}]};
const initial=()=>({state:'PRIVATE_BOOKED',opt:false,tolerance:5,started:false,aAccepted:false,bAccepted:false,verified:false,solo:false,match:null,error:''});
let model=initial(),role='A',scenario='happy';
function eligible(m,c){return m.opt&&m.started&&!m.verified&&c.solo&&c.destination===CONFIG.destination&&CONFIG.aPassengers+1<=CONFIG.capacity&&c.added<=m.tolerance&&c.available&&c.reachable}
function fare(m){return CONFIG.original-(m.verified?CONFIG.saving:0)}
function transition(m,a,v){let n={...m,error:''};switch(a){
case'opt':if(n.state==='PRIVATE_BOOKED')n.opt=v;break;
case'tolerance':if(n.state==='PRIVATE_BOOKED'&&[0,5,10].includes(v))n.tolerance=v;break;
case'solo':if(['PRIVATE_BOOKED','MATCH_PROPOSED'].includes(n.state)&&!n.bAccepted)n.solo=v;break;
case'start':if(n.state==='PRIVATE_BOOKED'){if(v!==CONFIG.otp){n.error='Incorrect demo OTP. Use 2468.';break}n.started=true;n.state='A_STARTED'}break;
case'search':if(n.state==='A_STARTED'&&n.opt&&!n.verified)n.state='SEARCHING_B';break;
case'find':if(n.state==='SEARCHING_B'){n.match=CONFIG.candidates.filter(c=>eligible(n,c)).sort((a,b)=>a.added-b.added||a.proximity-b.proximity)[0]||null;n.state=n.match?'MATCH_PROPOSED':'NO_ELIGIBLE_MATCH'}break;
case'acceptA':if(n.state==='MATCH_PROPOSED'){n.aAccepted=true;if(n.bAccepted)n.state='MATCH_ACCEPTED'}break;
case'acceptB':if(n.state==='MATCH_PROPOSED'&&n.solo){n.bAccepted=true;if(n.aAccepted)n.state='MATCH_ACCEPTED'}break;
case'decline':if(n.state==='MATCH_PROPOSED')n.state='MATCH_DECLINED';break;
case'expire':if(n.state==='MATCH_PROPOSED')n.state='MATCH_EXPIRED';break;
case'pickup':if(n.state==='MATCH_ACCEPTED')n.state='B_PICKUP';break;
case'noShow':if(n.state==='B_PICKUP')n.state='B_NO_SHOW';break;
case'verifyB':if(n.state==='B_PICKUP'){if(v!==CONFIG.otp){n.error='Incorrect demo OTP. Use 2468.';break}n.verified=true;n.state='B_OTP_VERIFIED'}break;
case'activate':if(n.state==='B_OTP_VERIFIED'&&n.verified)n.state='SHARE_ACTIVE';break;
case'complete':if(['SHARE_ACTIVE','NO_ELIGIBLE_MATCH','MATCH_DECLINED','MATCH_EXPIRED','B_NO_SHOW'].includes(n.state)||(n.state==='A_STARTED'&&!n.opt))n.state='COMPLETED';break;}return n}
function act(a,v){model=transition(model,a,v);if(model.state==='B_OTP_VERIFIED')model=transition(model,'activate');render()}
function reset(){model=initial();render()}function setRole(r){role=r;render()}function setScenario(s){scenario=s;reset()}
const button=(text,action,secondary=false,disabled=false)=>'<button class="'+(secondary?'secondary':'')+'" '+(disabled?'disabled':'')+' onclick="'+action+'">'+text+'</button>';
function RideStatus(title,sub){return '<span class="pill">'+(role==='D'?'DRIVER':'RIDER '+role)+' / '+(model.state==='COMPLETED'?'ARRIVED':model.verified?'SHARING ACTIVE':model.started?'TRIP IN PROGRESS':'RIDE PREVIEW')+'</span><h2>'+title+'</h2><p class="fine">'+sub+'</p><div class="row"><span class="fine">Destination</span><strong>'+CONFIG.destination+'</strong></div>'}
function FareSummary(){let b=role==='B';return '<div class="card '+(model.verified?'active':'')+'"><div class="row"><span>'+(b?'Smart Share fare':'Your fare')+'</span><span class="big">&#8377;'+(b?CONFIG.bFare+CONFIG.fee:fare(model))+'</span></div>'+(b?'<p class="fine">&#8377;110 ride + &#8377;10 service fee. Private reference: &#8377;200.<br>'+(model.verified?'Fare activated.':'Illustrative offer; fare activates at pickup verification.')+'</p>':model.verified?'<div class="row"><s>Original &#8377;400</s><strong>Saved &#8377;80</strong></div>':'<p class="fine">'+(model.opt?'Potential saving: up to &#8377;80 if a compatible rider joins. ':'')+'Your fare stays unchanged until B joins and verifies the pickup OTP.</p>')+'</div>'}
function SmartShareOptIn(){return '<div class="card"><label><input type="checkbox" '+(model.opt?'checked':'')+' onchange="act(\'opt\',this.checked)"><strong>Enable Smart Route Share</strong></label><p class="fine">One solo co-rider. Same destination. Matching begins after your trip starts.</p></div>'}
function TimeToleranceSelector(){return '<div class="card"><strong>Your maximum extra time</strong><p class="fine">Choose the maximum extra time you are comfortable with.</p><div class="choices">'+[0,5,10].map(v=>'<button aria-pressed="'+(v===model.tolerance)+'" class="'+(v===model.tolerance?'selected':'secondary')+'" onclick="act(\'tolerance\','+v+')">+'+v+' min</button>').join('')+'</div><p class="fine">We filter by predicted pickup impact. Live traffic could change actual arrival.</p></div>'}
function PassengerCard(){return '<div class="card"><strong>'+(role==='B'?'Rider A / one existing co-rider':'Rider B / solo traveller')+'</strong><p class="fine">Same destination / fictional rider identity</p></div>'}
function MatchOffer(){return '<div class="card"><div class="row"><div><div class="big">+'+model.match.added+' min</div><span class="fine">Predicted added time</span></div><div><div class="big">&#8377;'+(role==='B'?80:CONFIG.saving)+'</div><span class="fine">Potential saving</span></div></div><p class="fine">A selected a maximum of +'+model.tolerance+' min. Pickup ETA: 3 min (mock). One co-rider. Same destination. No more passenger pickups after joining.</p></div>'+PassengerCard()}
function OTPVerification(who){return '<div class="card"><label for="otp">'+(who==='A'?'Start your original ride':'Verify physical pickup of B')+'</label><p class="fine">Demo OTP: 2468. No SMS is sent.</p><input id="otp" type="text" inputmode="numeric" maxlength="4" placeholder="0000" aria-describedby="otpError"><p class="error" id="otpError" role="alert">'+model.error+'</p><div class="actions">'+button(who==='A'?'Verify A OTP & start':'Verify B OTP & activate share',"act('"+(who==='A'?'start':'verifyB')+"',document.getElementById('otp').value)")+'</div></div>'}
function NoShowState(){return RideStatus('Your original trip continues','Rider did not arrive. Continuing your original trip; your fare is unchanged.')+FareSummary()+'<div class="actions">'+button('Complete original trip',"act('complete')")+'</div>'}
function screen(){const s=model.state;
if(s==='PRIVATE_BOOKED'){if(role!=='A')return RideStatus('Waiting for A to start','No B search is possible before A verifies the pickup OTP.')+(role==='B'?'<div class="card"><label><input type="checkbox" '+(model.solo?'checked':'')+' onchange="act(\'solo\',this.checked)">I am travelling alone to Pune Railway Station</label></div>':'')+'<p class="fine">Use Rider A view to start the original ride.</p>';return RideStatus('Your ride, with more choice','Normal ride booked. Mock driver assigned. Pickup in 2 min.')+SmartShareOptIn()+(model.opt?TimeToleranceSelector():'')+FareSummary()+OTPVerification('A')}
if(s==='A_STARTED')return RideStatus('Your ride has started',model.opt?'You are in the vehicle. Matching can now use your active journey.':'Your ride remains private.')+FareSummary()+'<div class="actions">'+(role!=='B'?(model.opt?button('Look for a compatible rider',"act('search')"):button('Complete private trip',"act('complete')")):'<p class="fine">Waiting for the active ride to search.</p>')+'</div>';
if(s==='SEARCHING_B')return RideStatus('Looking for a compatible rider','Solo travellers to the same destination, within +'+model.tolerance+' min only.')+FareSummary()+'<div class="actions">'+(role!=='B'?button('Check matching result',"act('find')"):'<p class="fine">Waiting for a compatible active ride.</p>')+'</div>';
if(s==='MATCH_PROPOSED')return RideStatus(role==='B'?'Your Smart Share offer':'Compatible rider found','Review the proposed pickup before accepting.')+MatchOffer()+FareSummary()+'<div class="card"><div class="row"><span>A consent</span><b>'+(model.aAccepted?'Accepted':'Pending')+'</b></div><div class="row"><span>B consent</span><b>'+(model.bAccepted?'Accepted':'Pending')+'</b></div></div>'+(role==='B'?'<label><input type="checkbox" '+(model.solo?'checked':'')+' '+(model.bAccepted?'disabled':'')+' onchange="act(\'solo\',this.checked)">I am travelling alone</label>':'')+'<div class="actions">'+(role==='A'?button(model.aAccepted?'Waiting for B':'Accept share',"act('acceptA')",false,model.aAccepted)+button('Keep private',"act('decline')",true):role==='B'?button(model.bAccepted?'Waiting for A':'Accept offer',"act('acceptB')",false,!model.solo||model.bAccepted)+button('Decline',"act('decline')",true):'<p class="fine">Pickup instruction unlocks after both riders accept.</p>')+'</div>';
if(s==='MATCH_ACCEPTED')return RideStatus(role==='B'?'Driver approaching':'Heading to B','Both riders accepted. Your shared fare has not activated.')+PassengerCard()+'<div class="card"><div class="row"><span>Pickup ETA</span><b>3 min / mock</b></div><div class="row"><span>Impact / A maximum</span><b>+'+model.match.added+' / +'+model.tolerance+' min</b></div><p class="fine">'+(role==='B'?'Wait at the marked pickup. Have your OTP ready.':'Only one additional stop, then the shared destination.')+'</p></div>'+FareSummary()+'<div class="actions">'+(role==='D'?button('Arrive at B pickup',"act('pickup')"):'<p class="fine">Switch to Driver to simulate arrival.</p>')+'</div>';
if(s==='B_PICKUP')return RideStatus('At B pickup','Illustrative '+CONFIG.grace+'-minute grace period. Fare remains unchanged.')+FareSummary()+(scenario==='happy'?(role==='B'||role==='D'?OTPVerification('B'):'<p class="fine">Switch to B or Driver for pickup verification.</p>'):'<div class="card"><b>Waiting for B</b><p class="fine">No arrival in this scenario. Driver can simulate grace expiry.</p></div>')+'<div class="actions">'+(role==='D'?button('Grace elapsed / B no-show',"act('noShow')",true):'')+'</div>';
if(s==='SHARE_ACTIVE')return RideStatus('Shared ride started',role==='A'?'B joined and verified pickup. You saved Rs 80.':'Pickup verified. Continue together to the station.')+FareSummary()+PassengerCard()+'<div class="card"><b>No more passenger pickups</b><p class="fine">Matching closed. Shared destination / arrival in 18 min (mock).</p></div><div class="actions">'+button('Arrive at destination',"act('complete')")+'</div>';
if(s==='B_NO_SHOW')return role==='B'?RideStatus('Pickup missed','Driver continued the original trip. Your share fare was not activated.'):NoShowState();
if(['NO_ELIGIBLE_MATCH','MATCH_DECLINED','MATCH_EXPIRED'].includes(s))return RideStatus({NO_ELIGIBLE_MATCH:'No compatible rider',MATCH_DECLINED:'Ride remains private',MATCH_EXPIRED:'Offer expired'}[s],'Continue the original trip at the original fare.')+(role!=='B'?FareSummary():'<p class="fine">No shared ride activated.</p>')+'<div class="actions">'+button('Complete original trip',"act('complete')")+'</div>';
if(s==='COMPLETED')return RideStatus('Arrived at the station',model.verified?'One co-rider. One destination.':'The original ride is complete.')+(role==='B'&&!model.verified?'<p class="fine">No Smart Share fare activated for B.</p>':FareSummary())+'<p class="fine">Use presenter controls to replay.</p>';return ''}
function RouteMapMock(){let detour=['MATCH_PROPOSED','MATCH_ACCEPTED','B_PICKUP'].includes(model.state);return '<div class="map"><span class="maplabel">'+(detour?'One proposed pickup':model.verified?'Together to the station':'Your original route')+' / mock map</span><svg viewBox="0 0 360 210" role="img" aria-label="Illustrative route from A to the station'+(detour?' via B pickup':'')+'"><g stroke="white" stroke-width="14"><path d="M-10 55L380 160M70 -10L130 240M245 -10L200 240M-20 190L380 30"/></g><g fill="#d2dfca"><rect x="18" y="99" width="45" height="37" rx="8"/><rect x="280" y="57" width="58" height="33" rx="8"/></g><path d="M65 175L132 148L180 102L272 62" stroke="#19543c" stroke-width="7" fill="none" stroke-linecap="round"/>'+(detour?'<path d="M132 148L224 152L180 102" stroke="#c8832d" stroke-width="5" fill="none" stroke-dasharray="7 5"/><circle cx="224" cy="152" r="9" fill="#c8832d"/><text x="236" y="170" font-size="12">B pickup</text>':'')+'<circle cx="65" cy="175" r="10" fill="#19543c"/><circle cx="272" cy="62" r="10" fill="white" stroke="#19543c" stroke-width="5"/><text x="47" y="197" font-size="12">Rider A</text><text x="245" y="90" font-size="12">Station</text><rect x="145" y="112" width="27" height="16" rx="5" fill="#223d30"/></svg></div>'}
function DemoControls(){document.getElementById('roles').innerHTML=['A','B','D'].map(r=>button(r==='D'?'Driver':'Rider '+r,"setRole('"+r+"')",r!==role)).join('');document.getElementById('scenarios').innerHTML=button('Happy path',"setScenario('happy')",scenario!=='happy')+button('No-show',"setScenario('noShow')",scenario!=='noShow')+(model.state==='MATCH_PROPOSED'?button('Simulate offer expiry',"act('expire')",true):'');document.getElementById('inspect').textContent='State: '+model.state+'\nA started: '+model.started+'\nA fare: Rs '+fare(model)+'\nA / B accepted: '+model.aAccepted+' / '+model.bAccepted+'\nB verified: '+model.verified+'\n'+CONFIG.candidates.map(c=>c.id+' / +'+c.added+' min / '+(model.verified?'matching closed':!model.started?'not searched':eligible(model,c)?'eligible':'filtered out')).join('\n')}
function render(){document.getElementById('role').textContent=role==='D'?'Driver':'Rider '+role;document.getElementById('map').innerHTML=RouteMapMock();document.getElementById('screen').innerHTML=screen();DemoControls()}
function runChecks(){let r=[];const check=(name,ok)=>r.push({name,ok});let m=initial();m=transition(m,'opt',true);check('No search before A OTP',transition(m,'search').state==='PRIVATE_BOOKED');check('Incorrect A OTP blocked',!transition(m,'start','0000').started);m=transition(m,'start',CONFIG.otp);m=transition(m,'search');m=transition(m,'find');check('+4 offered / +10 filtered at +5',m.match.id==='B'&&!eligible(m,CONFIG.candidates[1]));check('Fare unchanged at proposal',fare(m)===400);m=transition(m,'acceptA');check('Both consents required',m.state==='MATCH_PROPOSED');check('B must confirm solo',transition(m,'acceptB').state==='MATCH_PROPOSED');m=transition(m,'solo',true);m=transition(m,'acceptB');m=transition(m,'pickup');check('Fare unchanged before B OTP',fare(m)===400);check('No-show retains Rs 400',fare(transition(m,'noShow'))===400);check('Wrong B OTP blocked',!transition(m,'verifyB','0000').verified);m=transition(m,'verifyB',CONFIG.otp);check('B verification state occurs',m.state==='B_OTP_VERIFIED');m=transition(m,'activate');check('OTP activates Rs 320',fare(m)===320&&m.state==='SHARE_ACTIVE');check('Matching closed after share',transition(m,'search').state==='SHARE_ACTIVE'&&!eligible(m,CONFIG.candidates[0]));check('Cannot add another pickup',transition(m,'pickup').state==='SHARE_ACTIVE');check('Completion retains fare',fare(transition(m,'complete'))===320);let z=initial();z=transition(z,'opt',true);z=transition(z,'tolerance',0);z=transition(z,'start',CONFIG.otp);z=transition(z,'search');z=transition(z,'find');check('+0 no eligible match',z.state==='NO_ELIGIBLE_MATCH');z={...z,state:'SEARCHING_B',tolerance:10};check('+10 picks least disruption',transition(z,'find').match.id==='B');check('Same destination required',!eligible(z,{...CONFIG.candidates[0],destination:'Other'}));check('B groups rejected',!eligible(z,{...CONFIG.candidates[0],solo:false}));let cap=CONFIG.capacity;CONFIG.capacity=1;check('Capacity enforced',!eligible(z,CONFIG.candidates[0]));CONFIG.capacity=cap;check('Availability required',!eligible(z,{...CONFIG.candidates[0],available:false}));check('Reachability required',!eligible(z,{...CONFIG.candidates[0],reachable:false}));check('Decline retains fare',fare(transition({...z,state:'MATCH_PROPOSED'},'decline'))===400);check('Expiry retains fare',fare(transition({...z,state:'MATCH_PROPOSED'},'expire'))===400);return r}
function checks(){document.getElementById('results').textContent=runChecks().map(r=>(r.ok?'PASS':'FAIL')+' '+r.name).join('\n')}
if(typeof document!=='undefined')render();

/* Guided presentation layer: actual consent and pickup transitions remain explicit. */
let guided=true;
const baseAct=act,baseScreen=screen;
const guideSteps={
PRIVATE_BOOKED:[0,'Set your comfort limit','You have a normal ride to the station. Sharing is optional.','Enable Smart Route Share, choose your maximum extra time, then start your ride with A OTP.'],
A_STARTED:[1,'Your original ride comes first','Matching starts only once you are in the vehicle. Your fare is still the normal fare.','Look for a compatible rider, or finish your private trip if sharing is off.'],
SEARCHING_B:[2,'Filter before offering','The system checks time, destination, solo travel and capacity before proposing anyone.','Check the result. With +5 selected, the +10-minute candidate is filtered out.'],
MATCH_PROPOSED:[3,'Two people. Two decisions.','A reviews the predicted delay. B reviews the fare, same destination and one-co-rider promise.','Accept as A, then confirm solo travel and explicitly accept as B. Neither acceptance changes A fare.'],
MATCH_ACCEPTED:[4,'One additional pickup','Both riders agreed. The driver receives one pickup instruction. A still pays the original fare.','Simulate the driver arriving at B pickup.'],
B_PICKUP:[5,'The moment that matters','A match becomes a shared ride only when B actually joins and pickup OTP is verified.','Enter B OTP to activate sharing, or simulate the no-show outcome.'],
SHARE_ACTIVE:[6,'Now the savings are real','B joined. A fare is reduced and matching is closed. Both riders continue to the same station.','Finish the journey. No additional passenger pickups can be added.'],
COMPLETED:[7,'A predictable trade-off','The demo ends at the shared destination. These are illustrative fares, not measured results.','Restart to compare the no-show scenario or a zero-minute tolerance.'],
B_NO_SHOW:[6,'No passenger, no discount','The driver leaves after the illustrative grace period. A continues the original journey at the original fare.','Complete the original trip, then compare with the happy path.'],
NO_ELIGIBLE_MATCH:[3,'Your limit is respected','No mock candidate fits your time limit. The system does not offer a slower match anyway.','Continue your original ride at the original fare.'],
MATCH_DECLINED:[3,'The choice stays yours','The proposal was declined. No sharing or discount was activated.','Complete the original private ride.'],
MATCH_EXPIRED:[3,'An unanswered offer is not a ride','The offer expired without a completed agreement. No sharing was activated.','Continue the original journey at the original fare.']
};
function guideRole(){if(!guided)return;if(model.state==='MATCH_PROPOSED')role=model.aAccepted?'B':'A';else if(model.state==='MATCH_ACCEPTED')role='D';else if(model.state==='B_PICKUP')role=scenario==='happy'?'B':'D';else role='A'}
act=function(a,v){baseAct(a,v)};
setRole=function(r){guided=false;role=r;render()};
function enableGuide(){guided=true;render()}
reset=function(){guided=true;model=initial();const out=document.getElementById('results');if(out)out.textContent='';render()};
FareSummary=function(){const b=role==='B',total=CONFIG.bFare+CONFIG.fee;return '<div class="card '+(model.verified?'active':'')+'"><div class="row"><span>'+(b?'Your shared fare':'Your fare')+'</span><span class="farelabel '+(model.verified?'confirmed':'')+'">'+(model.verified?'Confirmed':b?'Offer':'Unchanged')+'</span></div><div class="big">&#8377;'+(b?total:fare(model))+'</div>'+(b?'<p class="fine">&#8377;'+CONFIG.bFare+' ride + &#8377;'+CONFIG.fee+' service fee.<br>Private reference: &#8377;'+CONFIG.bReference+'. '+(model.verified?'Activated at pickup.':'Activates only after your pickup OTP.')+'</p>':model.verified?'<div class="row"><s>Original &#8377;'+CONFIG.original+'</s><strong>You saved &#8377;'+CONFIG.saving+'</strong></div>':'<p class="fine">'+(model.opt?'You could save up to <strong>&#8377;'+CONFIG.saving+'</strong> if a compatible rider joins. ':'')+'Your fare changes only after B joins and pickup OTP is verified.</p>')+'</div>'};
MatchOffer=function(){const savings=role==='B'?CONFIG.bReference-CONFIG.bFare-CONFIG.fee:CONFIG.saving;return '<div class="card"><div class="row"><div><div class="big">+'+model.match.added+' min</div><span class="fine">Predicted added time</span></div><div><div class="big">&#8377;'+savings+'</div><span class="fine">Potential saving</span></div></div><p class="fine"><strong>Your journey limit: +'+model.tolerance+' min.</strong><br>Pickup ETA: 3 min (illustrative). One co-rider. Same destination. No further passenger pickups after joining.</p></div>'+PassengerCard()};
screen=function(){let output=baseScreen();return output.replace('<p class="fine">Switch to Driver to simulate arrival.</p>','<p class="fine">The driver is on the way to the agreed pickup.</p>').replace('<p class="fine">Switch to B or Driver for pickup verification.</p>','<p class="fine">Waiting for the co-rider to join and verify pickup.</p>').replace('No arrival in this scenario. Driver can simulate grace expiry.','The passenger has not arrived within the illustrative grace period.').replace('Demo OTP: 2468. No SMS is sent.','Enter the pickup code. Demo code: 2468.').replace('Both riders accepted. Your shared fare has not activated.','Both riders accepted. Fare savings start only after pickup verification.')};
DemoControls=function(){document.getElementById('roles').innerHTML=['A','B','D'].map(r=>button(r==='D'?'Driver':'Rider '+r,"setRole('"+r+"')",r!==role)).join('');document.getElementById('scenarios').innerHTML='<div class="scenario"><button aria-pressed="'+(scenario==='happy')+'" onclick="setScenario(\'happy\')">Co-rider joins<small>See when the fare changes</small></button><button aria-pressed="'+(scenario==='noShow')+'" onclick="setScenario(\'noShow\')">Co-rider does not arrive<small>See the original fare protected</small></button></div>';const expire=document.getElementById('expire');if(expire)expire.disabled=model.state!=='MATCH_PROPOSED';document.getElementById('inspect').textContent='State: '+model.state+'\nA started: '+model.started+'\nA fare: Rs '+fare(model)+'\nA / B accepted: '+model.aAccepted+' / '+model.bAccepted+'\nB pickup verified: '+model.verified+'\n'+CONFIG.candidates.map(c=>c.id+' / +'+c.added+' min / '+(model.verified?'matching closed':!model.started?'not searched':eligible(model,c)?'eligible':'filtered out')).join('\n')};
render=function(){guideRole();document.getElementById('role').textContent=role==='D'?'Driver':'Rider '+role;document.getElementById('map').innerHTML=RouteMapMock();document.getElementById('screen').innerHTML=screen();DemoControls();const step=guideSteps[model.state];document.getElementById('progress').innerHTML=Array.from({length:8},(_,i)=>'<span class="'+(i<=step[0]?'done':'')+'" aria-hidden="true"></span>').join('');document.getElementById('guide').innerHTML='<div class="stepnumber">STEP '+(step[0]+1)+' OF 8</div><h3 class="guide-title">'+step[1]+'</h3><p>'+step[2]+'</p><div class="guide-action"><strong>Try this</strong>'+step[3]+'</div>'+(model.state==='PRIVATE_BOOKED'||model.state==='B_PICKUP'&&scenario==='happy'?'<div class="guide-tools">'+button('Fill demo OTP',"fillOTP()",true)+'</div>':'');document.getElementById('viewcaption').innerHTML='<strong>'+(role==='D'?'Driver view':role==='A'?'Original rider view':'Co-rider view')+'</strong><span>'+(guided?'Guided walkthrough':'Manual mode')+'</span>'};
function fillOTP(){const field=document.getElementById('otp');if(field){field.value=CONFIG.otp;field.focus()}}
if(typeof document!=='undefined')render();
